import Navbar from "../components/Navbar/Navbar"

export const metadata = {
  title: 'Test',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
